name: sm4rty
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_svg: 1.1.6
  google_fonts: 3.0.1
  auto_size_text: 3.0.0
  iconly: ^1.0.1
  liquid_progress_indicator: ^0.4.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - lib/app/data/images/
  uses-material-design: true

